services:
  - type: web
    name: lims
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "waitress-serve --port=$PORT app:app"
    envVars:
      - key: SECRET_KEY
        sync: false
      - key: DATABASE_URI
        sync: false
